# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # or the branches you want to trigger the pipeline

pool:
   vmImage: 'windows-latest'

steps:
  # Step 1: Install Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Step 2: Install dependencies
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      playwright install
    displayName: 'Install dependencies'

  # Step 3: Run Playwright tests
  - script: |
      pytest test_day6_day7_final.py --html=results/report.html --junit-xml=results/report.xml
    displayName: 'Run Playwright Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'Junit'
      testRunTitle: 'test results'
      testResultsFiles: '**/results/report.xml'
    condition: succeededOrFailed()


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/results'
      artifact: 'Test Reports'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()
